### ISSUE TITLE
Broken box in item pile

### ISSUE THREAD

**Issue by Hermitus** [callanh/pathos-official#6]
In the windows version, if a broken box is in a pile and one double-clicks the floor, it only opens the box -- it doesn't bring up the select-and-take option. The box must be moved of the pile first.

**Comment by callanh** [comment]
Thanks for this suggestion, I was busy with the public release of Kaloi Opus, so I didn't want to risk making a change at the last moment. Anyway, I've now changed it so that if you have a pile of items, double-click/tap will always open the floor menu. I've released a new Windows Desktop version with this change if you want to test it out.

**Comment by h1data** [comment]
After this fix, it seems the ground menu appeared instead of the contents in the box when the player unlocked or kicked one of the piled chests.
